/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as LocationRouteImport } from './routes/location'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrayerTrackerRouteImport } from './routes/prayer-tracker'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as JournalCompleteStatisticRouteImport } from './routes/journal/complete-statistic'
import { Route as KhazanahIndexRouteImport } from './routes/khazanah/index'
import { Route as KhazanahCategoryRouteImport } from './routes/khazanah/$category'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as JournalDailyJournalIndexRouteImport } from './routes/journal/daily-journal/index'
import { Route as JournalDailyJournalCreateRouteImport } from './routes/journal/daily-journal/create'
import { Route as KhazanahVerseIdRouteImport } from './routes/khazanah/verse.$id'
import { Route as JournalDailyJournalCreateStepRouteImport } from './routes/journal/daily-journal/create.$step'
import { Route as JournalDailyJournalEntryEntryIdRouteImport } from './routes/journal/daily-journal/entry.$entryId'
import { Route as JournalDailyJournalThemeIdRouteImport } from './routes/journal/daily-journal/theme.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTrackerRoute = PrayerTrackerRouteImport.update({
  id: '/prayer-tracker',
  path: '/prayer-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalCompleteStatisticRoute =
  JournalCompleteStatisticRouteImport.update({
    id: '/journal/complete-statistic',
    path: '/journal/complete-statistic',
    getParentRoute: () => rootRouteImport,
  } as any)
const KhazanahIndexRoute = KhazanahIndexRouteImport.update({
  id: '/khazanah/',
  path: '/khazanah/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhazanahCategoryRoute = KhazanahCategoryRouteImport.update({
  id: '/khazanah/$category',
  path: '/khazanah/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalDailyJournalIndexRoute =
  JournalDailyJournalIndexRouteImport.update({
    id: '/journal/daily-journal/',
    path: '/journal/daily-journal/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalDailyJournalCreateRoute =
  JournalDailyJournalCreateRouteImport.update({
    id: '/journal/daily-journal/create',
    path: '/journal/daily-journal/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const KhazanahVerseIdRoute = KhazanahVerseIdRouteImport.update({
  id: '/khazanah/verse/$id',
  path: '/khazanah/verse/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalDailyJournalCreateStepRoute =
  JournalDailyJournalCreateStepRouteImport.update({
    id: '/$step',
    path: '/$step',
    getParentRoute: () => JournalDailyJournalCreateRoute,
  } as any)
const JournalDailyJournalEntryEntryIdRoute =
  JournalDailyJournalEntryEntryIdRouteImport.update({
    id: '/journal/daily-journal/entry/$entryId',
    path: '/journal/daily-journal/entry/$entryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalDailyJournalThemeIdRoute =
  JournalDailyJournalThemeIdRouteImport.update({
    id: '/journal/daily-journal/theme/$id',
    path: '/journal/daily-journal/theme/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/edit-profile': typeof EditProfileRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/prayer-tracker': typeof PrayerTrackerRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/journal/complete-statistic': typeof JournalCompleteStatisticRoute
  '/khazanah/$category': typeof KhazanahCategoryRoute
  '/khazanah/': typeof KhazanahIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/journal/daily-journal/create': typeof JournalDailyJournalCreateRouteWithChildren
  '/khazanah/verse/$id': typeof KhazanahVerseIdRoute
  '/journal/daily-journal/': typeof JournalDailyJournalIndexRoute
  '/journal/daily-journal/create/$step': typeof JournalDailyJournalCreateStepRoute
  '/journal/daily-journal/entry/$entryId': typeof JournalDailyJournalEntryEntryIdRoute
  '/journal/daily-journal/theme/$id': typeof JournalDailyJournalThemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/edit-profile': typeof EditProfileRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/prayer-tracker': typeof PrayerTrackerRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/journal/complete-statistic': typeof JournalCompleteStatisticRoute
  '/khazanah/$category': typeof KhazanahCategoryRoute
  '/khazanah': typeof KhazanahIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/journal/daily-journal/create': typeof JournalDailyJournalCreateRouteWithChildren
  '/khazanah/verse/$id': typeof KhazanahVerseIdRoute
  '/journal/daily-journal': typeof JournalDailyJournalIndexRoute
  '/journal/daily-journal/create/$step': typeof JournalDailyJournalCreateStepRoute
  '/journal/daily-journal/entry/$entryId': typeof JournalDailyJournalEntryEntryIdRoute
  '/journal/daily-journal/theme/$id': typeof JournalDailyJournalThemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/edit-profile': typeof EditProfileRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/prayer-tracker': typeof PrayerTrackerRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/journal/complete-statistic': typeof JournalCompleteStatisticRoute
  '/khazanah/$category': typeof KhazanahCategoryRoute
  '/khazanah/': typeof KhazanahIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/journal/daily-journal/create': typeof JournalDailyJournalCreateRouteWithChildren
  '/khazanah/verse/$id': typeof KhazanahVerseIdRoute
  '/journal/daily-journal/': typeof JournalDailyJournalIndexRoute
  '/journal/daily-journal/create/$step': typeof JournalDailyJournalCreateStepRoute
  '/journal/daily-journal/entry/$entryId': typeof JournalDailyJournalEntryEntryIdRoute
  '/journal/daily-journal/theme/$id': typeof JournalDailyJournalThemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/edit-profile'
    | '/location'
    | '/login'
    | '/prayer-tracker'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/journal/complete-statistic'
    | '/khazanah/$category'
    | '/khazanah/'
    | '/api/auth/$'
    | '/journal/daily-journal/create'
    | '/khazanah/verse/$id'
    | '/journal/daily-journal/'
    | '/journal/daily-journal/create/$step'
    | '/journal/daily-journal/entry/$entryId'
    | '/journal/daily-journal/theme/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/edit-profile'
    | '/location'
    | '/login'
    | '/prayer-tracker'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/journal/complete-statistic'
    | '/khazanah/$category'
    | '/khazanah'
    | '/api/auth/$'
    | '/journal/daily-journal/create'
    | '/khazanah/verse/$id'
    | '/journal/daily-journal'
    | '/journal/daily-journal/create/$step'
    | '/journal/daily-journal/entry/$entryId'
    | '/journal/daily-journal/theme/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/edit-profile'
    | '/location'
    | '/login'
    | '/prayer-tracker'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/journal/complete-statistic'
    | '/khazanah/$category'
    | '/khazanah/'
    | '/api/auth/$'
    | '/journal/daily-journal/create'
    | '/khazanah/verse/$id'
    | '/journal/daily-journal/'
    | '/journal/daily-journal/create/$step'
    | '/journal/daily-journal/entry/$entryId'
    | '/journal/daily-journal/theme/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EditProfileRoute: typeof EditProfileRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  PrayerTrackerRoute: typeof PrayerTrackerRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  JournalCompleteStatisticRoute: typeof JournalCompleteStatisticRoute
  KhazanahCategoryRoute: typeof KhazanahCategoryRoute
  KhazanahIndexRoute: typeof KhazanahIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  JournalDailyJournalCreateRoute: typeof JournalDailyJournalCreateRouteWithChildren
  KhazanahVerseIdRoute: typeof KhazanahVerseIdRoute
  JournalDailyJournalIndexRoute: typeof JournalDailyJournalIndexRoute
  JournalDailyJournalEntryEntryIdRoute: typeof JournalDailyJournalEntryEntryIdRoute
  JournalDailyJournalThemeIdRoute: typeof JournalDailyJournalThemeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-tracker': {
      id: '/prayer-tracker'
      path: '/prayer-tracker'
      fullPath: '/prayer-tracker'
      preLoaderRoute: typeof PrayerTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/complete-statistic': {
      id: '/journal/complete-statistic'
      path: '/journal/complete-statistic'
      fullPath: '/journal/complete-statistic'
      preLoaderRoute: typeof JournalCompleteStatisticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khazanah/': {
      id: '/khazanah/'
      path: '/khazanah'
      fullPath: '/khazanah/'
      preLoaderRoute: typeof KhazanahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khazanah/$category': {
      id: '/khazanah/$category'
      path: '/khazanah/$category'
      fullPath: '/khazanah/$category'
      preLoaderRoute: typeof KhazanahCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/daily-journal/': {
      id: '/journal/daily-journal/'
      path: '/journal/daily-journal'
      fullPath: '/journal/daily-journal/'
      preLoaderRoute: typeof JournalDailyJournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/daily-journal/create': {
      id: '/journal/daily-journal/create'
      path: '/journal/daily-journal/create'
      fullPath: '/journal/daily-journal/create'
      preLoaderRoute: typeof JournalDailyJournalCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khazanah/verse/$id': {
      id: '/khazanah/verse/$id'
      path: '/khazanah/verse/$id'
      fullPath: '/khazanah/verse/$id'
      preLoaderRoute: typeof KhazanahVerseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/daily-journal/create/$step': {
      id: '/journal/daily-journal/create/$step'
      path: '/$step'
      fullPath: '/journal/daily-journal/create/$step'
      preLoaderRoute: typeof JournalDailyJournalCreateStepRouteImport
      parentRoute: typeof JournalDailyJournalCreateRoute
    }
    '/journal/daily-journal/entry/$entryId': {
      id: '/journal/daily-journal/entry/$entryId'
      path: '/journal/daily-journal/entry/$entryId'
      fullPath: '/journal/daily-journal/entry/$entryId'
      preLoaderRoute: typeof JournalDailyJournalEntryEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/daily-journal/theme/$id': {
      id: '/journal/daily-journal/theme/$id'
      path: '/journal/daily-journal/theme/$id'
      fullPath: '/journal/daily-journal/theme/$id'
      preLoaderRoute: typeof JournalDailyJournalThemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JournalDailyJournalCreateRouteChildren {
  JournalDailyJournalCreateStepRoute: typeof JournalDailyJournalCreateStepRoute
}

const JournalDailyJournalCreateRouteChildren: JournalDailyJournalCreateRouteChildren =
  {
    JournalDailyJournalCreateStepRoute: JournalDailyJournalCreateStepRoute,
  }

const JournalDailyJournalCreateRouteWithChildren =
  JournalDailyJournalCreateRoute._addFileChildren(
    JournalDailyJournalCreateRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EditProfileRoute: EditProfileRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  PrayerTrackerRoute: PrayerTrackerRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  JournalCompleteStatisticRoute: JournalCompleteStatisticRoute,
  KhazanahCategoryRoute: KhazanahCategoryRoute,
  KhazanahIndexRoute: KhazanahIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  JournalDailyJournalCreateRoute: JournalDailyJournalCreateRouteWithChildren,
  KhazanahVerseIdRoute: KhazanahVerseIdRoute,
  JournalDailyJournalIndexRoute: JournalDailyJournalIndexRoute,
  JournalDailyJournalEntryEntryIdRoute: JournalDailyJournalEntryEntryIdRoute,
  JournalDailyJournalThemeIdRoute: JournalDailyJournalThemeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
